# Generated by Django 3.2.19 on 2023-06-04 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='title')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(blank=True, max_length=32, null=True, verbose_name='location')),
                ('website', models.CharField(blank=True, max_length=64, null=True, verbose_name='website')),
            ],
            options={
                'verbose_name': 'company',
                'verbose_name_plural': 'companies',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='title')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.SmallIntegerField(choices=[(0, 'Created'), (1, 'Application sent'), (2, 'Active'), (3, 'Positive response'), (4, 'Contract signed'), (-1, 'Negative response'), (-2, 'Resigned')], default=0, verbose_name='status')),
                ('employment_type', models.CharField(choices=[('None', 'None'), ('B2B', 'Business to business'), ('PERMANENT', 'Permanent'), ('CONTRACT', 'Contract')], default='None', max_length=16, null=True, verbose_name='employment type')),
                ('level', models.PositiveSmallIntegerField(choices=[(0, 'Not provided'), (1, 'Junior'), (2, 'Regular'), (3, 'Senior')], default=0, verbose_name='experience level')),
                ('skills_required', models.JSONField(blank=True, default=dict, verbose_name='skills required')),
                ('skills_optional', models.JSONField(blank=True, default=dict, verbose_name='skills optional')),
                ('earnings_max', models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='earnings max')),
                ('earnings_min', models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='earnings min')),
                ('application_sent_on', models.DateTimeField(blank=True, default=None, null=True, verbose_name='application sent date and time')),
                ('remote', models.BooleanField(default=True, verbose_name='remote')),
                ('location', models.CharField(blank=True, max_length=32, null=True, verbose_name='location')),
                ('description', models.TextField(blank=True, max_length=2048, null=True, verbose_name='description')),
                ('comments', models.TextField(blank=True, max_length=512, null=True, verbose_name='comments')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.company')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'offer',
                'verbose_name_plural': 'offers',
                'ordering': ['-updated_on', '-created_on'],
            },
        ),
        migrations.CreateModel(
            name='RecruitmentStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='title')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, max_length=2048, null=True, verbose_name='description')),
                ('status', models.SmallIntegerField(choices=[(0, 'Created'), (1, 'Planned'), (2, 'Waiting for response'), (3, 'Positive response'), (-1, 'Negative response'), (-2, 'Resigned')], default=0, verbose_name='status')),
                ('scheduled_on', models.DateTimeField(blank=True, null=True, verbose_name='scheduled on')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='manager.offer')),
            ],
            options={
                'verbose_name': 'recruitment step',
                'verbose_name_plural': 'recruitment steps',
                'ordering': ['-updated_on', '-created_on'],
            },
        ),
    ]
