# Generated by Django 3.2.19 on 2023-06-05 15:21

from django.db import migrations, transaction

# TODO ADD MUCH MORE!
SKILLS = ["Python", "Java", "Golang"]
STEP_TYPES = ["other", "introductory interview", "tech interview", "online quiz", "task online"]


def forwards_func(apps, schema_editor):
    User = apps.get_model("users", "User")
    Skill = apps.get_model("manager", "Skill")
    StepType = apps.get_model("manager", "StepType")
    db_alias = schema_editor.connection.alias

    with transaction.atomic():
        bot, _ = User.objects.get_or_create(email="automat@nixonsparrow.pl")
        skills = [Skill(name=skill) for skill in SKILLS]
        Skill.objects.using(db_alias).bulk_create(skills)
        step_types = [StepType(name=step_type, added_by_id=bot.id) for step_type in STEP_TYPES]
        StepType.objects.using(db_alias).bulk_create(step_types)


def reverse_func(apps, schema_editor):
    User = apps.get_model("users", "User")
    Skill = apps.get_model("manager", "Skill")
    StepType = apps.get_model("manager", "StepType")
    db_alias = schema_editor.connection.alias
    Skill.objects.using(db_alias).delete()
    StepType.objects.using(db_alias).delete()
    User.objects.using(db_alias).filter(email="automat@nixonsparrow.pl").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
